// flow-typed signature: d914de597aed22e7509bcbaaadc60c78
// flow-typed version: <<STUB>>/@dlghq/babel-preset-dialog_v4.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dlghq/babel-preset-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dlghq/babel-preset-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dlghq/babel-preset-dialog/index' {
  declare module.exports: $Exports<'@dlghq/babel-preset-dialog'>;
}
declare module '@dlghq/babel-preset-dialog/index.js' {
  declare module.exports: $Exports<'@dlghq/babel-preset-dialog'>;
}
