// flow-typed signature: 5293a12ac277bde3c6b1170b9f31be64
// flow-typed version: <<STUB>>/@dlghq/eslint-config-dialog_v3.4.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dlghq/eslint-config-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dlghq/eslint-config-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dlghq/eslint-config-dialog/base' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/globals' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/best-practices' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/es2015' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/index' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/node' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/possible-errors' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/strict-mode' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/stylistic-issues' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/eslint/variables' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/react/index' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/react/jsx' {
  declare module.exports: any;
}

declare module '@dlghq/eslint-config-dialog/src/rules/react/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dlghq/eslint-config-dialog/base.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/base'>;
}
declare module '@dlghq/eslint-config-dialog/index' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog'>;
}
declare module '@dlghq/eslint-config-dialog/index.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog'>;
}
declare module '@dlghq/eslint-config-dialog/src/globals.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/globals'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/best-practices.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/best-practices'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/es2015.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/es2015'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/index.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/index'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/node.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/node'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/possible-errors.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/possible-errors'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/strict-mode.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/strict-mode'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/stylistic-issues.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/stylistic-issues'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/eslint/variables.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/eslint/variables'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/react/index.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/react/index'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/react/jsx.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/react/jsx'>;
}
declare module '@dlghq/eslint-config-dialog/src/rules/react/react.js' {
  declare module.exports: $Exports<'@dlghq/eslint-config-dialog/src/rules/react/react'>;
}
